version: '3.8'
services:
  saleor:
    image: saleor/saleor:stable
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - SECRET_KEY=a5e1066c-6869-4a84-b00f-b27947864063
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/saleor
      - REDIS_URL=redis://redis:6379/0
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - ../data/redisdata:/data
